### ISSUE TITLE
Prep of ISED Issuer(s) sequence

### ISSUE THREAD

**Issue by swcurran** [bcgov/ised-business-banking-initiative#5]
We need to adjust the ISED Business Banking Initiative verifiable credential issuers.  The model has changed a little, so here is the sequence that I would like to issue.  @esune -- please review and let me know what we have in place and what we need to change.  @alexgmetcalf , I'd appreciate it if you can do the words at the landing page (what to do) and post-issue page (what to do next).  This issue covers what is in place, what has changed in the demo, what minimum changes that we need to do.  I was going to add a thing about being able to minimize the QR codes in use, but I don't think that's realistic.

## What Is In Place?

A sequence of three issuers:

- Issuer: https://bcreg-issuer-dev.pathfinder.gov.bc.ca/
   - Authentication is Test Services Card, issue is of a "Verified Person" credential from BC Registries
- Issuer: https://bcreg-registration-issuer-dev.pathfinder.gov.bc.ca/
   - Authentication is "Verified Person" credential, issue is of a "Verified Registration" credential from BC Registries
- Issuer: https://bcreg-relationship-issuer-dev.pathfinder.gov.bc.ca/
   - Authentication is "Verified Person" and "Verified Registration" credential from BC Registries
- Verifier: https://bcbank-verifier-dev.pathfinder.gov.bc.ca/
   - Authentication is all three issued credentials.

## What is Changing

The first credential is going to be issued by IDIM -- Citizen Services -- instead of BC Registries.  As well, there will be no unique identifier associated with the verified person -- just as there is no identifier in the DIACC/Peter Watkins verified person implementation.

@esune -- will use the site listed above updated, or will you use the DIACC/Peter Watkins site?  I see pros and cons for both.

As well, the contents/attribute names in the credentials have changed and will be provided.

## Minimum Changes

Change the first issuer to be from BC Citizen Services, the identifier removed, and change all of the subsequent authentications to use that credential. As such, there needs to be a different DID from the BC Registries DID. As well, change the value of the "identifier" for the "verified person" in the "verified relationship" credential to be the full name, since there is no longer a number to use.

## Documentation:

Here is the flow I'm thinking we should follow:

- We give the person the URL for the BC Registries "Verified Organization" landing page.  On that, we tell them that they need a "Verified Person" credential to proceed and a link to that site to open a new page/tabl, leaving the existing one open.  The instructions should tell the user to come back to this site when done.
   - Alternatively, we should have a landing page for the whole process
- The verified person should have instructions to get that, including about the need to use the Services Card mobile app. 
   - In an inside voice -- we can explain how to do this on the dev/test site with the test BC Services Card IDs that we have.
- The "Verified Person" "post issue" page should not be specific to the ISED Business Banking Initiative use case, but generic, so the user will have to remember to go back to the BC Registries page...
- The user will continue through the issuing process on the "Verified Organization" Issuer.
- On the "post-issue" page, the instructions should say that "Normally, the Verified Relationship credential should be automatically issued, but for this we have to do another authentication and issue process" and put in a link to the "Verified Relationship" issuer. 
- On the Verified Relationship issuer page, explain the rest of the process and that there should not be extra QR codes.
- On the "post-issue" page, talk about using the credentials now held to open a bank account, and provide a link to the sample verifier.
- On the landing page for the verifier, make it like you are on a website to create a bank account.

We should probably have that site create a bank account and issue a credential for the bank account....

@alexgmetcalf -- could you please do the text for the examples -- using language that is helpful to business owners.  The whole "verified relationship" thing is not needed.

Also worthwhile is going through the issuance of the last two creds twice to simulate a person that has more than one company.  What does the holder experience look like when you have credentials for multiple companies?

See the bottom of this document for the new attributes in the credentials and how to populate them.

## The Verifiable Credentials

The following cover the new attributes and how to populate them.  I have put "blank" to indicate the field is not populated.  Ideally, that will be either `""` or `null` (which I think might be implemented -- at least in Aries Cloud Agent Python).  If it has to have a value, please put "Not Issued".

### Verified Person

- verifiedPersonKey - blank
- givenName - from Services Card
- additionalName (Optional) - middle name from Service Card (if any) or  "Not Issued"
- familyName - from Services Card
- streetAddress - from Services Card
- city - from Services Card
- province - from Services Card
- country - from Services Card
- postalCode - from Services Card
- dateOfBirth - "Not Issued"
- phoneNumber - "Not Issued"
- alternatePhoneNumber (Optional) - blank
- email - blank
- gender (Optional) - blank
- issuer - "BC Citizen Services"
- issueDate - date of issue from Services Card
- expirationDate - date of expiration from Services Card (or  "Not Issued")
- credentialStatus - "Issued"
- levelOfAssurance (Optional) - blank

### Verified Organization

- verifiedOrganizationKey - generate per BC RegID format
- businessNumber - generate - 9 digits
- entityType - BC Corp
- registeredLegalName - let the user type in the name
- homeJurisdictionLegalName (Optional) - blank
- alternateLegalName (Optional) - blank
- operatingName (Optional) - blank
- streetAddress - allow user to enter full address (autocomplete??? :-) )
- city
- province
- country
- postalCode
- legislation (Optional) - blank
- registeredJurisdiction (Optional) - "BC"
- homeJurisdiction - "BC"
- director001FullName (Optional) - user entered
- director001StreetAddress (Optional) - blank
- director001City (Optional) - blank
- director001Province (Optional) - blank
- director001Country (Optional) - blank
- director001PostalCode (Optional) - blank
- director001CanadianResident (Optional) - blank
- registrationDate
- director002FullName (Optional) - user entered
- director002StreetAddress (Optional) - blank
- director002City (Optional) - blank
- director002Province (Optional) - blank
- director002Country (Optional) - blank
- director002PostalCode (Optional) - blank
- director002CanadianResident (Optional) - blank
- registrationDate - today() or today() - random(1500)
- registrationExpiryDate (Optional) - registrationRenewalEffectiveDate + 1 year
- registrationRenewalEffective (Optional) - today() or today() - random(60)
- registeredLegalNameEffective - registrationDate
- homeJurisdictionLegalNameEffective - registrationDate
- entityStatus - "Active"
- entityStatusEffective - registrationDate
- issuer - "BC"
- issueDate - today()
- expirationDate - registrationExpiryDate
- credentialStatus - "Active"

### Verified Relationship

- verifiedPersonKey - blank
- verifiedPersonIssuer - "BC Citizen Services"
- verifiedOrganizationKey - from Verified Organization
- verifiedOrganizationIssuer - from Verified Organization
- registeredLegalName - from Verified Organization
- relationship - "Director"
- relationshipDescription - blank
- relationshipStatus - "Active"
- relationshipStatusEffective (Optional) - registrationDate  from Verified Organization
- issuer - "BC Registries"
- issueDate - today()
- expirationDate - blank
- credentialStatus - "Active"

**Comment by esune** [comment]
For reference on what attributes are available through BCSC: https://selfservice-demo.pathfinder.gov.bc.ca/help/help-dev

**Comment by esune** [comment]
# Deployed Services

Ministry of Citizens' Services issuer:
* DEV: https://bcgov-citz-issuer-dev.apps.silver.devops.gov.bc.ca
* TEST: https://bcgov-citz-issuer-test.apps.silver.devops.gov.bc.ca
* PROD: https://bcgov-citz-issuer.apps.silver.devops.gov.bc.ca

BC Registries Verified Organization issuer:
* DEV: https://bcreg-registration-issuer-dev.apps.silver.devops.gov.bc.ca
* TEST: https://bcreg-registration-issuer-test.apps.silver.devops.gov.bc.ca
* PROD: https://bcreg-registration-issuer.apps.silver.devops.gov.bc.ca

BC Registries Verified Relationship issuer:
* DEV: https://bcreg-relationship-issuer-dev.apps.silver.devops.gov.bc.ca
* TEST: https://bcreg-relationship-issuer-test.apps.silver.devops.gov.bc.ca
* PROD: https://bcreg-relationship-issuer.apps.silver.devops.gov.bc.ca

Business Bank Verifier:
* DEV: https://business-bank-verifier-dev.apps.silver.devops.gov.bc.ca
* TEST: https://business-bank-verifier-test.apps.silver.devops.gov.bc.ca
* PROD: https://business-bank-verifier.apps.silver.devops.gov.bc.ca

Once this PR is merged, changes to the pages with wording can be PR'd directly to this repo - @alexgmetcalf. Tag me in it and I'll take care of merging and updating deployments.

----

# What Changed

All the issuers and verifiers were reconfigured from scratch, including all of the integrations with `vc-authn` and Keycloak, in each environment. PR #6 contains all of the changes currently deployed (165 files, yikes!).

----

# Final Notes

The schemas used are very big, and have a number of claims that are named the same (e.g.: `issuer`). This means that:
- the wallet apps are slow at building/displaying the proof-request on a VERY recent mobile device, I am not sure what it will be on older devices. Additionally, it is impossible to see clearly everything that is being requested on-screen as there is just not enough space.
- because of the verbosity of the schemas, the verifier is not showing all of the requested claims as verified: I suspect it is because of the payload being too big, but will need to investigate more to understand what's up.
- the forms in the issuer webapps are a first cut of what they could look like and be, they could be improved and cleaned up more once the requirements are finalized.
- the `PROD` environment will require a working BC Services Card to sign-in the first issuer. `DEV` and `TEST` use test credentials.
